version: '2'
services:
  s3:
    image: minio/minio:RELEASE.2023-04-07T05-28-58Z
    restart: "unless-stopped"
    volumes:
      - ./minio/data:/data
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
    command: server --address 0.0.0.0:9000 --console-address ":${MINIO_PORT}" /data
    ports:
        - "127.0.0.1:9000:9000"
        -  ${MINIO_PORT}:${MINIO_PORT}
  backend-postgres:
    container_name: postgres_db_apod
    restart: always
    image: postgres:13
    environment:
      - DEBUG=false
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/data/postgres
    command: -p ${POSTGRES_PORT}