version: '2'
services:
  rest-backend:
    container_name: apod-rest-backend
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./backend/m2:/root/.m2
    depends_on:
      - backend-postgres
  minio:
    image: minio/minio:RELEASE.2021-01-05T05-22-38Z
    restart: "unless-stopped"
    volumes:
      - ./minio/data:/data
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
    command: server --address 0.0.0.0:9000 --console-address ":${MINIO_PORT}" /data
    ports:
      - "127.0.0.1:9000:9000"
      - ${MINIO_PORT}:${MINIO_PORT}
  createbuckets:
    image: minio/mc:RELEASE.2021-01-05T05-03-58Z
    depends_on:
      - minio
        ## To create Bucket with no public policy, add the following lines
        ## after configuring the host, but before "exit 0;"
        ## change "bucketnpa" to your desired bucket name
        ##
      ## /usr/bin/mc mb minio/bucketnpa;
      ## /usr/bin/mc policy none minio/bucketnpa;
    environment:
#      - MINIO_ACCESS_KEY=minio-access-key
#      - MINIO_SECRET_KEY=minio-secret-key
      - BUCKET_NAME=apod
#      - ENDPOINT=http://minio:9000
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://localhost:9000 minio minio123
      /usr/bin/mc mb minio/apod;
      exit 0;
      "
  backend-postgres:
    container_name: postgres_db_apod
    restart: always
    image: postgres:13
    environment:
      - DEBUG=false
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/data/postgres
    command: -p ${POSTGRES_PORT}
