env: "local" # local, development, production

nasa_api_key: "B3tYLXowtRCwboU4yOuNWjHlzenYJULLXfb50LGJ"

http_server:
  address: "0.0.0.0:8000"
  timeout: 4s
  idle_timeout: 30s

minio_auth_data:
  url:  "localhost:9000"
  user: "minio"
  password: "minio123"
